sonar.projectKey=nahushr_opscards
sonar.organization=nahushr
sonar.projectName=OpsCards
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=src,examples/src
sonar.exclusions=**/dist/**,**/node_modules/**,examples/public/**
sonar.coverage.exclusions=**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=600
